version: '3.8'

services:
  # Ruby app service
  app:
    image: nupmanyu/devops-app:latest
    container_name: ruby-app
    ports:
      - "4000:4000"
    restart: always
    networks:
      - app-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1  
        delay: 10s  
      rollback_config:
        parallelism: 1  
        delay: 10s 

  # Prometheus service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Ensure you have the prometheus.yml file ready
    ports:
      - "9090:9090"
    networks:
      - app-network

  # Grafana service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"  # Set Grafana admin password
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

