apiVersion: v1
kind: Service
metadata:
  name: dev-app-service
spec:
  type: NodePort
  selector:
    app: dev-app
  ports:
    - port: 4000         # Port inside the cluster
      targetPort: 4000   # Port your container is listening on
      nodePort: 30007    # External port (can be auto-assigned if you omit this line)
